# Generated by Django 4.0.3 on 2022-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_project_taskassign_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='acnt_monthdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_fromdate', models.DateField(blank=True, null=True)),
                ('month_todate', models.DateField(blank=True, null=True)),
                ('month_workingdays', models.IntegerField()),
                ('month_holidays', models.IntegerField()),
            ],
        ),
    ]
